### ISSUE TITLE
0.2 Todo

### ISSUE THREAD

**Issue by jonathanhliu21** [jonyboi396825/COM-Server#112]
- [x] #96 
- [ ] #111 
- [ ] Fix all documentation issues
  - [ ] #115 
  - [ ] Test all examples
- [ ] Update changelog
- [ ] **Test on all platforms**
- [ ] Update version on `__init__.py` and `setup.cfg` to 0.3b0 on develop branch
  - [ ] Create new 0.3.x branch from develop before above changes - develop PR to 0.3.x after above changes
- [ ] Update release sphinx conf.py
- [ ] Set default version on readthedocs to 0.2.x
